# Generated by Django 5.0.3 on 2024-03-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('protagonists', models.CharField(max_length=500)),
                ('poster', models.ImageField(upload_to='posters/')),
                ('trailer', models.FileField(upload_to='trailers/')),
                ('start_date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('coming_up', 'Coming Up'), ('starting', 'Starting'), ('running', 'Running'), ('finished', 'Finished')], default='coming_up', max_length=50)),
                ('ranking', models.IntegerField(default=0)),
                ('last_ranking_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
